// Starter templates — accurately reproducing the 4 distinct broadcast designs
// from the Telegram bot (breaking_news, opinion_quote, economy_report, sports_highlight).

import type { TemplateModel } from './model'
import { CANVAS_WIDTH, CANVAS_HEIGHT, newLayer, defaultRound, defaultBumper } from './model'

export const STARTER_TEMPLATES: TemplateModel[] = [
  // 1. Breaking News
  {
    id: 'breaking_news',
    name: 'خبر عاجل · Breaking News',
    description: 'قالب الأخبار العاجلة والتغطية المباشرة المفتوحة',
    width: CANVAS_WIDTH,
    height: CANVAS_HEIGHT,
    fps: 30,
    duration: 5,
    backgroundColor: '#0b0b0f',
    accentColor: '#e63946',
    bumper: defaultBumper(),
    layers: [
      newLayer('background', { overlayOpacity: 0.65 }),
      newLayer('accentBar', {
        name: 'Top Red Bar',
        backgroundColor: '#e63946',
        x: 0,
        y: 0,
        width: 100,
        height: 12,
        animation: { type: 'none', duration: 0, delay: 0, easing: 'linear' },
      }),
      newLayer('logo', {
        name: 'Brand Logo',
        text: 'كشيدة',
        fontSize: 48,
        fontWeight: 900,
        x: 8,
        y: 4,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.05, easing: 'ease-out' },
      }),
      newLayer('label', {
        name: 'Breaking Badge',
        labelAr: 'عاجل',
        labelEn: 'BREAKING',
        backgroundColor: '#e63946',
        fontSize: 24,
        x: 8,
        y: 65,
        textAlign: 'start',
        animation: { type: 'slide-right', duration: 0.35, delay: 0.1, easing: 'ease-out' },
      }),
      newLayer('headline', {
        name: 'Main Headline',
        text: 'اكتب هنا عنوان الخبر العاجل الرئيسي',
        fontSize: 54,
        fontWeight: 900,
        x: 8,
        y: 72,
        width: 84,
        textAlign: 'start',
        color: '#ffffff',
        animation: { type: 'slide-up', duration: 0.4, delay: 0.15, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Subheadline',
        text: 'تفاصيل إضافية حول التغطية الإخبارية والتطورات الميدانية',
        fontSize: 28,
        fontWeight: 600,
        x: 8,
        y: 84,
        width: 84,
        textAlign: 'start',
        color: 'rgba(255,255,255,0.85)',
        animation: { type: 'slide-up', duration: 0.35, delay: 0.25, easing: 'ease-out' },
      }),
      newLayer('timestamp', {
        name: 'Timestamp',
        text: 'منذ قليل',
        fontSize: 20,
        x: 8,
        y: 91,
        textAlign: 'start',
        color: 'rgba(255,255,255,0.6)',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.3, easing: 'ease-out' },
      }),
      newLayer('footer', {
        name: 'Live Bottom Bar',
        text: 'LIVE NEWS · kashida.io',
        fontSize: 20,
        fontWeight: 700,
        x: 0,
        y: 96,
        width: 100,
        textAlign: 'start',
        color: 'rgba(255,255,255,0.7)',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.3, easing: 'ease-out' },
      }),
    ],
    rounds: [
      defaultRound({
        headline: 'اكتب هنا عنوان الخبر العاجل الرئيسي',
        subheadline: 'تفاصيل إضافية حول التغطية الإخبارية والتطورات الميدانية',
        labelAr: 'عاجل',
        labelEn: 'BREAKING',
        accentColor: '#e63946',
        backgroundColor: '#0b0b0f',
        timestamp: 'منذ قليل',
      }),
    ],
  },

  // 2. Opinion & Quote
  {
    id: 'opinion_quote',
    name: 'اقتباس وتصريح · Quote & Statement',
    description: 'قالب اقتباس التصريحات الرسمية ببطاقة زجاجية فاخرة',
    width: CANVAS_WIDTH,
    height: CANVAS_HEIGHT,
    fps: 30,
    duration: 5,
    backgroundColor: '#0b0b0f',
    accentColor: '#e63946',
    bumper: defaultBumper({ accentColor: '#e63946', backgroundColor: '#0b0b0f' }),
    layers: [
      newLayer('background', { overlayOpacity: 0.65 }),
      newLayer('label', {
        name: 'Quote Badge',
        labelAr: 'اقتباس وتصريح',
        labelEn: 'STATEMENT',
        backgroundColor: '#e63946',
        fontSize: 22,
        x: 8,
        y: 4,
        textAlign: 'start',
        animation: { type: 'slide-right', duration: 0.35, delay: 0.05, easing: 'ease-out' },
      }),
      newLayer('logo', {
        name: 'Brand Logo',
        text: 'كشيدة',
        fontSize: 38,
        fontWeight: 900,
        x: 75,
        y: 4,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.05, easing: 'ease-out' },
      }),
      newLayer('card', {
        name: 'Frosted Quote Card',
        x: 6,
        y: 42,
        width: 88,
        height: 520,
        backgroundColor: 'rgba(15,23,42,0.88)',
        border: '2px solid rgba(255,255,255,0.18)',
        borderRadius: 32,
        backdropBlur: 20,
        animation: { type: 'slide-up', duration: 0.4, delay: 0.1, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Quote Icon',
        text: '“',
        fontSize: 90,
        fontWeight: 900,
        color: '#e63946',
        x: 10,
        y: 44,
        width: 80,
        textAlign: 'center',
        animation: { type: 'zoom-in', duration: 0.35, delay: 0.15, easing: 'ease-out' },
      }),
      newLayer('headline', {
        name: 'Quoted Statement',
        text: 'نعمل بكل عزم وإصرار على تحقيق رؤية التحول والتطوير المستمر',
        fontSize: 42,
        fontWeight: 800,
        x: 10,
        y: 52,
        width: 80,
        textAlign: 'center',
        color: '#ffffff',
        animation: { type: 'slide-up', duration: 0.4, delay: 0.2, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Speaker Attribution',
        text: '— تصريح رسمي رفيع المستوى',
        fontSize: 26,
        fontWeight: 700,
        x: 10,
        y: 72,
        width: 80,
        textAlign: 'center',
        color: '#e63946',
        animation: { type: 'fade-in', duration: 0.35, delay: 0.3, easing: 'ease-out' },
      }),
      newLayer('footer', {
        name: 'Footer Bar',
        text: 'STATEMENT LIVE · kashida.io',
        fontSize: 22,
        fontWeight: 700,
        x: 0,
        y: 96,
        width: 100,
        textAlign: 'start',
        color: 'rgba(255,255,255,0.7)',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.3, easing: 'ease-out' },
      }),
    ],
    rounds: [
      defaultRound({
        headline: 'نعمل بكل عزم وإصرار على تحقيق رؤية التحول والتطوير المستمر',
        subheadline: '— تصريح رسمي رفيع المستوى',
        labelAr: 'اقتباس وتصريح',
        labelEn: 'STATEMENT',
        accentColor: '#e63946',
        backgroundColor: '#0b0b0f',
      }),
    ],
  },

  // 3. Economy & Markets
  {
    id: 'economy_report',
    name: 'تقرير اقتصادي · Economy & Markets',
    description: 'قالب الأسواق والتقارير المالية والمؤشرات الاقتصادية',
    width: CANVAS_WIDTH,
    height: CANVAS_HEIGHT,
    fps: 30,
    duration: 5,
    backgroundColor: '#080b12',
    accentColor: '#FFB703',
    bumper: defaultBumper({ accentColor: '#FFB703', backgroundColor: '#080b12' }),
    layers: [
      newLayer('background', { overlayOpacity: 0.7 }),
      newLayer('accentBar', {
        name: 'Top Gold Bar',
        backgroundColor: '#FFB703',
        x: 0,
        y: 0,
        width: 100,
        height: 12,
        animation: { type: 'none', duration: 0, delay: 0, easing: 'linear' },
      }),
      newLayer('logo', {
        name: 'Economy Logo',
        text: 'كشيدة اقتصاد',
        fontSize: 38,
        fontWeight: 900,
        color: '#ffffff',
        x: 8,
        y: 4,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.05, easing: 'ease-out' },
      }),
      newLayer('label', {
        name: 'Markets Badge',
        labelAr: 'اقتصاد والمال',
        labelEn: 'MARKETS',
        backgroundColor: '#FFB703',
        fontSize: 22,
        x: 60,
        y: 4,
        textAlign: 'start',
        animation: { type: 'slide-left', duration: 0.35, delay: 0.08, easing: 'ease-out' },
      }),
      newLayer('card', {
        name: 'Frosted Market Card',
        x: 6,
        y: 50,
        width: 88,
        height: 500,
        backgroundColor: 'rgba(15,23,42,0.92)',
        border: '2px solid rgba(255,183,3,0.4)',
        borderRadius: 28,
        backdropBlur: 16,
        animation: { type: 'slide-up', duration: 0.4, delay: 0.1, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Ticker Header',
        text: '📊 مؤشرات أسواق المال',
        fontSize: 20,
        fontWeight: 800,
        color: '#FFB703',
        x: 10,
        y: 53,
        width: 80,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.18, easing: 'ease-out' },
      }),
      newLayer('headline', {
        name: 'Market Headline',
        text: 'ارتفاع مؤشرات الأسهم وتداولات قياسية في جلسة اليوم',
        fontSize: 46,
        fontWeight: 900,
        x: 10,
        y: 60,
        width: 80,
        textAlign: 'start',
        color: '#ffffff',
        animation: { type: 'slide-up', duration: 0.4, delay: 0.2, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Market Subheadline',
        text: 'نمو ملحوظ في قطاعات التكنولوجيا والطاقة البديلة',
        fontSize: 26,
        fontWeight: 600,
        x: 10,
        y: 74,
        width: 80,
        textAlign: 'start',
        color: 'rgba(255,255,255,0.85)',
        animation: { type: 'slide-up', duration: 0.35, delay: 0.28, easing: 'ease-out' },
      }),
      newLayer('footer', {
        name: 'Market Watch Footer',
        text: 'MARKET WATCH LIVE · kashida.io',
        fontSize: 22,
        fontWeight: 800,
        x: 0,
        y: 96,
        width: 100,
        textAlign: 'start',
        color: '#FFB703',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.3, easing: 'ease-out' },
      }),
    ],
    rounds: [
      defaultRound({
        headline: 'ارتفاع مؤشرات الأسهم وتداولات قياسية في جلسة اليوم',
        subheadline: 'نمو ملحوظ في قطاعات التكنولوجيا والطاقة البديلة',
        labelAr: 'اقتصاد والمال',
        labelEn: 'MARKETS',
        accentColor: '#FFB703',
        backgroundColor: '#080b12',
      }),
    ],
  },

  // 4. Sports Highlight
  {
    id: 'sports_highlight',
    name: 'تغطية رياضية · Sports Highlight',
    description: 'قالب التغطيات والبطولات الرياضية الديناميكية',
    width: CANVAS_WIDTH,
    height: CANVAS_HEIGHT,
    fps: 30,
    duration: 5,
    backgroundColor: '#06110e',
    accentColor: '#00F5D4',
    bumper: defaultBumper({ accentColor: '#00F5D4', backgroundColor: '#06110e' }),
    layers: [
      newLayer('background', { overlayOpacity: 0.65 }),
      newLayer('logo', {
        name: 'Sports Logo',
        text: 'كشيدة رياضة',
        fontSize: 40,
        fontWeight: 900,
        color: '#ffffff',
        x: 8,
        y: 4,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.05, easing: 'ease-out' },
      }),
      newLayer('label', {
        name: 'Sports Badge',
        labelAr: 'تغطية رياضية',
        labelEn: 'SPORTS',
        backgroundColor: '#00F5D4',
        fontSize: 22,
        x: 58,
        y: 4,
        textAlign: 'start',
        animation: { type: 'slide-left', duration: 0.35, delay: 0.08, easing: 'ease-out' },
      }),
      newLayer('card', {
        name: 'Dynamic Sports Card',
        x: 6,
        y: 50,
        width: 88,
        height: 500,
        backgroundColor: 'rgba(6,17,14,0.92)',
        border: '2px solid #00F5D4',
        borderRadius: 28,
        backdropBlur: 16,
        animation: { type: 'slide-up', duration: 0.4, delay: 0.1, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Trophy Header',
        text: '🏆 متابعة رياضية حصرية',
        fontSize: 22,
        fontWeight: 900,
        color: '#00F5D4',
        x: 10,
        y: 53,
        width: 80,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.18, easing: 'ease-out' },
      }),
      newLayer('headline', {
        name: 'Sports Headline',
        text: 'فوز ساحق وتتويج مستحق في نهائي البطولة',
        fontSize: 48,
        fontWeight: 900,
        x: 10,
        y: 60,
        width: 80,
        textAlign: 'start',
        color: '#ffffff',
        animation: { type: 'slide-up', duration: 0.4, delay: 0.2, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Match Details Subheadline',
        text: 'أداء بطولي وحسم النتيجة في اللحظات الأخيرة من المباراة',
        fontSize: 28,
        fontWeight: 700,
        x: 10,
        y: 74,
        width: 80,
        textAlign: 'start',
        color: '#ffffff',
        animation: { type: 'slide-up', duration: 0.35, delay: 0.28, easing: 'ease-out' },
      }),
      newLayer('footer', {
        name: 'Sports Live Footer',
        text: 'SPORTS LIVE · kashida.io',
        fontSize: 22,
        fontWeight: 900,
        x: 0,
        y: 96,
        width: 100,
        textAlign: 'start',
        color: '#00F5D4',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.3, easing: 'ease-out' },
      }),
    ],
    rounds: [
      defaultRound({
        headline: 'فوز ساحق وتتويج مستحق في نهائي البطولة',
        subheadline: 'أداء بطولي وحسم النتيجة في اللحظات الأخيرة من المباراة',
        labelAr: 'تغطية رياضية',
        labelEn: 'SPORTS',
        accentColor: '#00F5D4',
        backgroundColor: '#06110e',
      }),
    ],
  },

  // 5. 🎴 Reel Solid Card News (Instagram Reels / Arabi21 style)
  {
    id: 'reel_card_news',
    name: '🎴 بطاقة ريلز إخبارية (Reel News Card)',
    description: 'قالب بطاقة الأخبار العريضة لريلز وتيك توك مع حركة الكلمات المتقطعة وشارة خاصة',
    width: CANVAS_WIDTH,
    height: CANVAS_HEIGHT,
    fps: 30,
    duration: 5,
    backgroundColor: '#0b0b0f',
    accentColor: '#E41E3F',
    bumper: defaultBumper({ accentColor: '#E41E3F' }),
    layers: [
      newLayer('background', { overlayOpacity: 0.45 }),
      newLayer('logo', {
        name: 'Brand Logo',
        text: 'عربي21',
        fontSize: 52,
        fontWeight: 900,
        x: 8,
        y: 4,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.4, delay: 0.05, easing: 'ease-out' },
      }),
      newLayer('label', {
        name: 'Special Badge',
        labelAr: 'خاص',
        labelEn: 'SPECIAL',
        backgroundColor: '#E41E3F',
        fontSize: 22,
        x: 8,
        y: 12,
        textAlign: 'start',
        animation: { type: 'pop-bounce', duration: 0.5, delay: 0.1, easing: 'back-out' },
      }),
      newLayer('shape', {
        id: '8kj5fmb2',
        name: 'Shape Object',
        shapeType: 'rounded-box',
        backgroundColor: '#ff0000',
        borderRadius: 20,
        width: 86,
        height: 20,
        x: 7,
        y: 65,
        rotation: 0,
        animation: { type: 'wipe-rtl', duration: 1.5, delay: 0.2, easing: 'ease-out' },
        animationOut: { type: 'slide-left', duration: 0.4, delay: 0.4, easing: 'ease-out' },
      }),
      newLayer('headline', {
        name: 'Main Headline',
        text: 'مراسم دفن 10 من ضحايا مذبحة سربرنيتسا',
        fontSize: 46,
        fontWeight: 900,
        x: 9,
        y: 68,
        width: 82,
        textAlign: 'center',
        color: '#ffffff',
        animation: { type: 'word-stagger', duration: 0.5, delay: 0.25, easing: 'ease-out', stagger: 0.08 },
      }),
      newLayer('subheadline', {
        name: 'Subheadline',
        text: 'تغطية ميدانية مباشرة للفعاليات والمراسم الرسمية',
        fontSize: 24,
        fontWeight: 600,
        x: 9,
        y: 77,
        width: 82,
        textAlign: 'center',
        color: 'rgba(255,255,255,0.92)',
        animation: { type: 'fade-in', duration: 0.35, delay: 0.4, easing: 'ease-out' },
      }),
      newLayer('footer', {
        name: 'Source Attribution',
        text: 'عربي21 · رويترز',
        fontSize: 18,
        fontWeight: 700,
        x: 8,
        y: 93,
        width: 84,
        textAlign: 'start',
        color: 'rgba(255,255,255,0.75)',
        animation: { type: 'fade-in', duration: 0.3, delay: 0.5, easing: 'ease-out' },
      }),
    ],
    rounds: [
      defaultRound({
        headline: 'مراسم دفن 10 من ضحايا مذبحة سربرنيتسا',
        subheadline: 'تغطية ميدانية مباشرة للفعاليات والمراسم الرسمية',
        labelAr: 'خاص',
        labelEn: 'SPECIAL',
        accentColor: '#E41E3F',
        backgroundColor: '#0b0b0f',
      }),
    ],
  },

  // 6. ⚽ Stacked Highlight Pills (Instagram Reels / Mbappé video style)
  {
    id: 'sports_pill_highlight',
    name: '⚽ كبسولات ريلز الرياضية (Stacked Highlight Pills)',
    description: 'قالب الكبسولات الملوّنة المتراكمة لعناوين الريلز والرياضة والترندات مع شارة المونديال والمصدر',
    width: CANVAS_WIDTH,
    height: CANVAS_HEIGHT,
    fps: 30,
    duration: 5,
    backgroundColor: '#0b0b0f',
    accentColor: '#7C3AED',
    bumper: {
      enabled: true,
      showIntro: false,
      showInterstitial: false,
      showOutro: true,
      duration: 3.5,
      backgroundColor: '#F8FAFC',
      accentColor: '#E41E3F',
      logoText: 'عربي21',
      slogan: 'f · 𝕏 ·  ·  ·  | Arabi21News · www.Arabi21.com',
      animation: { type: 'zoom-in', duration: 0.6, delay: 0.1, easing: 'ease-out' },
      animationOut: { type: 'none', duration: 0, delay: 0, easing: 'linear' },
    },
    layers: [
      newLayer('background', { overlayOpacity: 0.3 }),
      newLayer('logo', {
        name: 'Brand Logo',
        text: 'عربي21',
        fontSize: 52,
        fontWeight: 900,
        x: 8,
        y: 18,
        textAlign: 'start',
        animation: { type: 'fade-in', duration: 0.4, delay: 0.05, easing: 'ease-out' },
      }),
      newLayer('label', {
        name: 'Tournament Badge',
        labelAr: 'مونديال 🏆',
        labelEn: '',
        backgroundColor: '#7C3AED',
        fontSize: 24,
        x: 65,
        y: 18,
        textAlign: 'center',
        animation: { type: 'wipe-rtl', duration: 0.45, delay: 0.1, easing: 'ease-out' },
      }),
      newLayer('timestamp', {
        name: 'Credit & Date',
        text: '@20minxo 🎥 · 2026-07-10',
        fontSize: 18,
        fontWeight: 700,
        x: 68,
        y: 25,
        width: 26,
        textAlign: 'end',
        color: '#ffffff',
        animation: { type: 'fade-in', duration: 0.35, delay: 0.2, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Location Tag',
        text: 'أمريكا 📍',
        fontSize: 28,
        fontWeight: 900,
        x: 52,
        y: 52,
        width: 40,
        textAlign: 'end',
        color: '#ffffff',
        animation: { type: 'pop-bounce', duration: 0.4, delay: 0.1, easing: 'ease-out' },
      }),
      newLayer('headline', {
        name: 'Pill 1 — Top Purple Action',
        text: 'مشجع برازيلي يهدي',
        backgroundColor: '#7C3AED',
        borderRadius: 22,
        fontSize: 38,
        fontWeight: 900,
        x: 18,
        y: 58.5,
        width: 64,
        height: 70,
        textAlign: 'center',
        color: '#ffffff',
        animation: { type: 'wipe-rtl', duration: 0.45, delay: 0.15, easing: 'ease-out' },
      }),
      newLayer('subheadline', {
        name: 'Pill 2 — Middle Orange Subject',
        text: 'كيليان مبابي قميص',
        backgroundColor: '#EA580C',
        borderRadius: 22,
        fontSize: 38,
        fontWeight: 900,
        x: 15,
        y: 66,
        width: 70,
        height: 70,
        textAlign: 'center',
        color: '#ffffff',
        animation: { type: 'wipe-rtl', duration: 0.45, delay: 0.28, easing: 'ease-out' },
      }),
      newLayer('footer', {
        name: 'Pill 3 — Bottom Orange Object',
        text: 'منتخب البرازيل',
        backgroundColor: '#EA580C',
        borderRadius: 22,
        fontSize: 38,
        fontWeight: 900,
        x: 23,
        y: 73.5,
        width: 54,
        height: 70,
        textAlign: 'center',
        color: '#ffffff',
        animation: { type: 'wipe-rtl', duration: 0.45, delay: 0.4, easing: 'ease-out' },
      }),
    ],
    rounds: [
      defaultRound({
        id: 'r1',
        name: 'مشهد 1: العنوان الرئيسي',
        headline: 'مشجع برازيلي يهدي',
        subheadline: 'كيليان مبابي قميص',
        labelAr: 'مونديال 🏆',
        labelEn: '',
        accentColor: '#7C3AED',
        backgroundColor: '#0b0b0f',
        duration: 6,
      }),
      defaultRound({
        id: 'r2',
        name: 'مشهد 2: تصريح وتعريف اللاعب',
        headline: 'شكرًا كيليان',
        subheadline: 'كيليان مبابي · لاعب كرة قدم فرنسي',
        labelAr: 'مونديال 🏆',
        labelEn: '',
        accentColor: '#EA580C',
        backgroundColor: '#0b0b0f',
        duration: 7.5,
      }),
    ],
  },
]

export function getStarterTemplate(id: string): TemplateModel | undefined {
  const cleanId = id.trim().toLowerCase().replace(/\.html$/, '')
  const found = STARTER_TEMPLATES.find((t) => t.id === cleanId)
  if (found) {
    return JSON.parse(JSON.stringify(found))
  }
  return undefined
}

